export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILES = "GET_PROFILES";
export const GET_REPOS = "GET_REPOS";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const ACCOUNT_DELETED = "ACCOUNT_DELETED";
export const GET_POSTS = "GET_POSTS";
export const GET_POST = "GET_POST";
export const POST_ERROR = "POST_ERROR";
export const UPDATE_LIKES = "UPDATE_LIKES";
export const DELETE_POST = "DELETE_POST";
export const ADD_POST = "ADD_POST";
export const ADD_COMMENT = "ADD_COMMENT";
export const REMOVE_COMMENT = "REMOVE_COMMENT";
export const UPDATE_STATUS = "UPDATE_STATUS";
export const GET_USERS = "GET_USERS";
export const CLEAR_USERS = "CLEAR_USERS";
export const CHANGE_STATUS = "CHANGE_STATUS";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const PRODUCTS_ERROR = "PRODUCTS_ERROR";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const PRODUCTS_SUCCESS = "PRODUCTS_SUCCESS";
export const FILTER_PRODUCT = "FILTER_PRODUCT";
export const CLEAR_FILTER = "CLEAR_FILTER";
export const FILTER_RAW_MATERIALS = "FILTER_RAW_MATERIALS";
export const CLEAR_FILTER_RAW_MATERIALS = "CLEAR_FILTER_RAW_MATERIALS";

export const GET_CUSTOMERS = "GET_CUSTOMERS";
export const CUSTOMERS_ERROR = "CUSTOMERS_ERROR";
export const CUSTOMERS_SUCCESS = "CUSTOMERS_SUCCESS";
export const CUSTOMERS_PROFILE = "CUSTOMERS_PROFILE";

export const GET_RAW_MATERIALS = "GET_RAW_MATERIALS";
export const GET_SUPPLIERS = "GET_SUPPLIERS";
export const GET_SIZES = "GET_SIZES";
export const GET_STOCKS = "GET_STOCKS";
export const RAW_MATERIALS_ERROR = "RAW_MATERIALS_ERROR";
export const SIZE_ERROR = "SIZE_ERROR";
export const SUPPLIERS_ERROR = "SUPPLIERS_ERROR";
export const STOCKS_ERROR = "STOCKS_ERROR";
export const ADD_RAW_MATERIAL = "ADD_RAW_MATERIAL";
export const ADD_SUPPLIER = "ADD_SUPPLIER";
export const ADD_SIZE = "ADD_SIZE";
export const ADD_STOCK = "ADD_STOCK";

export const FEEDBACKS_SUCCESS = "FEEDBACKS_SUCCESS";
export const FEEDBACKS_ERROR = "FEEDBACKS_ERROR";
export const GET_FEEDBACKS = "GET_FEEDBACKS";

export const PAYMENTS_SUCCESS = "PAYMENTS_SUCCESS";
export const PAYMENTS_ERROR = "PAYMENTS_ERROR";
export const GET_PAYMENTS = "GET_PAYMENTS";

export const GET_ORDERS = "GET_ORDERS";
export const ORDER_ERROR = "ORDER_ERROR";

export const GET_CATEGORY = "GET_CATEGORY";
export const CATEGORY_ERROR = "CATEGORY_ERROR";
export const ADD_CATEGORY = "ADD_CATEGORY";

export const GET_PRODUCTION_DETAILS = "GET_PRODUCTION_DETAILS";
export const CLEAR_PRODUCTION_DETAILS = "CLEAR_PRODUCTION_DETAILS";
export const PRODUCTION_DETAILS_ERROR = "PRODUCTION_DETAILS_ERROR";




export const GET_SALES = "GET_SALES";
export const SALES_ERROR = "SALES_ERROR";

export const GET_USER = "GET_USER";
export const USERS_ERROR = "USERS_ERROR";
